# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

windowrule = match:float 0, match:workspace w[tv1], border_size 0, rounding 0
windowrule = match:float 0, match:workspace f[1], border_size 0, rounding 0

windowrule = match:class ^(org.telegram.desktop)$, workspace name:telegram silent

windowrule = match:class ^(discord)$, workspace name:discord silent
windowrule = match:class ^(whatsdesk)$, workspace name:whatsapp silent
windowrule = match:class ^(thunderbird)$, workspace name:mail silent

windowrule = match:class ^(obsidian)$, workspace special:obsidian silent

windowrule = match:class ^(btop)$, float 1, fullscreen 1

windowrule =  match:class ^(pavucontrol)$, float 1

windowrule = match:class ^(filepicker)$, float 1

windowrule = match:class ^(popup)$, float 1, center 1, size (monitor_w*0.7) (monitor_h*0.5)

windowrule = match:class ^(calendar)$, float 1, center 1, size 602 880

windowrule = match:title ^(Picture-in-Picture)$, float 1, pin 1 (monitor_w*0.22) (monitor_h*0.24), move onscreen 100% 0%

windowrule = match:class ^(steam)$, workspace name:games silent
windowrule = match:float 1, match:title ^(Steam)$, center 1
windowrule = match:title ^(Friends List)$, float 1, size 20% 70%

windowrule = match:title ^(World of Warcraft)$, fullscreen 1

windowrule = match:class ^(powerline)$, float 1, pin 1, dim_around 1
