[colors.primary]
background = "#0e0e10"

[env]
TERM = "xterm-256color"

[window.padding]
x = 4
y = 4

[font]
size = 14.0

[font.bold]
family = "Iosevka Term SS01"
style = "SemiBold"

[font.normal]
family = "Iosevka Term SS01"
style = "Regular"

[font.italic]
family = "Iosevka Term SS01"
style = "Italic"

[[keyboard.bindings]]
chars = "\u001B[27;5;9~"
key = "Tab"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[27;6;9~"
key = "Tab"
mods = "Control|Shift"
