# general.import = ["~/.config/alacritty/nord.toml"]
general.import = [
    # "~/.config/alacritty/nord.toml"
    # "~/.config/alacritty/catppuccin-mocha.toml",
    "~/.config/alacritty/gruvbox.toml",
]

[env]
TERM = "xterm-256color"

[window]
decorations = "None"

[window.padding]
x = 4
y = 0

[font]
size = 14

[font.bold]
family = "Iosevka Term"
style = "Medium"

[font.normal]
family = "Iosevka Term"
style = "Regular"

[font.italic]
family = "Iosevka Term"
style = "Oblique"

[font.bold_italic]
family = "Iosevka Term"
style = "SemiBold Oblique"

[[keyboard.bindings]]
chars = "\u001b[9;5u"
key = "Tab"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001b[9;6u"
key = "Tab"
mods = "Shift | Control"


[[keyboard.bindings]]
chars = "\u001b[72;6u"
key = "H"
mods = "Shift | Control"

[[keyboard.bindings]]
chars = "\u001b[76;6u"
key = "L"
mods = "Shift | Control"
