# import = ["~/.config/alacritty/everforest.toml"]
import = ["~/.config/alacritty/nord.toml"]

[env]
TERM = "xterm-256color"

[window]
decorations = "None"

[window.padding]
x = 4
y = 0

[font]
size = 12

[font.bold]
family = "Iosevka Term"
style = "Medium"

[font.normal]
family = "Iosevka Term"
style = "Regular"

[font.italic]
family = "Iosevka Term"
style = "Oblique"

[font.bold_italic]
family = "Iosevka Term"
style = "SemiBold Oblique"

[[keyboard.bindings]]
chars = "\u001B[27;5;9~"
key = "Tab"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[27;6;9~"
key = "Tab"
mods = "Control|Shift"
